language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: WITH_CMAKE=true BUILD_TEST=false
    - os: linux
      compiler: gcc
      dist: trusty
      sudo: required
      env: WITH_CMAKE=false BUILD_TEST=false
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      sudo: required
      env: WITH_CMAKE=true BUILD_TEST=false
    - os: osx
      compiler: clang
      osx_image: xcode7.3
      sudo: required
      env: WITH_CMAKE=false BUILD_TEST=false
  allow_failures:
    - env: WITH_CMAKE=false BUILD_TEST=false
    - os: osx

addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libxt-dev
    - libxi-dev

git:
  submodules: false

before_install:
  - export NUM_THREADS=4
  - export cwd=$(pwd)
  - export BUILD_DIR=$cwd/build
  - export SV_EXTERNALS_DIR=$cwd/Externals
  - export SV_EXTERNALS_BUILD_DIR=$SV_EXTERNALS_DIR/build
  - export SV_EXTERNALS_BIN_DIR=$SV_EXTERNALS_BUILD_DIR/sv_externals/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$SV_EXTERNALS_BIN_DIR/qt-5.4.2/lib
  - export SV_CODE_DIR=$cwd/Code
  - export SV_TEST_DIR=$HOME/test/
  - export SCRIPTS=$cwd/travis
  - $SCRIPTS/travis_cmake_get_externals.sh
  - if $BUILD_TEST; then $SCRIPTS/travis_get_test_data.sh; fi

script: $SCRIPTS/travis_build_and_test.sh
